services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $listBuilderFactory: '@sulu_core.doctrine_list_builder_factory'


  _instanceof:
    Sulu\Bundle\AdminBundle\Admin\Admin:
      tags: ['sulu.admin', {name: 'sulu.context', context: 'admin'}]

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Sulu\Bundle\StylingBundle:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,DataFixtures,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Sulu\Bundle\StylingBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  # following service definitions will be removed in the website context of sulu
  Sulu\Bundle\StylingBundle\Admin\:
    resource: '../../Admin'
    tags: [{name: 'sulu.context', context: 'admin'}]

  Sulu\Bundle\StylingBundle\Controller\Admin\:
    resource: '../..//Controller/Admin'
    tags: [{name: 'sulu.context', context: 'admin'}]